# Generated by Django 4.0.6 on 2022-07-17 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('delete', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('private', 'private'), ('semiprivate', 'semiprivate'), ('public', 'public')], default='private', max_length=11, verbose_name='type')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=250, verbose_name='name terms')),
                ('slug', models.CharField(max_length=250, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('end_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Created Time')),
                ('time', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('cracreator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=250, verbose_name='name terms')),
                ('slug', models.CharField(max_length=250, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('end_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Created Time')),
                ('time', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='term.term')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
