# Generated by Django 4.0.6 on 2022-07-18 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='term',
        ),
        migrations.AddField(
            model_name='term',
            name='session',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='term.session'),
        ),
    ]
