# Generated by Django 4.0.6 on 2022-07-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0005_remove_session_end_at_remove_session_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='slug',
        ),
        migrations.AlterField(
            model_name='term',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='description'),
        ),
    ]
