# Generated by Django 4.0.6 on 2022-07-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0006_remove_term_slug_alter_term_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='pay',
            field=models.BooleanField(default=False),
        ),
    ]
