# Generated by Django 4.0.6 on 2022-07-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0007_term_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='student',
        ),
    ]
