# Generated by Django 4.0.6 on 2022-07-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('user', 'user'), ('coche', 'coche'), ('admin', 'admin')], default='user', max_length=11, unique=True, verbose_name='level'),
        ),
    ]
