# Generated by Django 4.0.6 on 2022-07-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_cracreator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('user', 'user'), ('coche', 'coche'), ('admin', 'admin')], default='user', max_length=11, verbose_name='level'),
        ),
    ]
